name: Build and Deploy

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DO_APP_ID: 5fdf484c-3859-4387-bc2e-533ae5059772

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Spell check
        run: npm run spell

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        run: |
          IMAGE_TAG=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker build -t ${IMAGE_TAG,,} .
          docker push ${IMAGE_TAG,,}

      - name: Deploy to DigitalOcean
        env:
          DO_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        run: |
          http_code=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
            -H "Authorization: Bearer $DO_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{}' \
            "https://api.digitalocean.com/v2/apps/${{ env.DO_APP_ID }}/deployments")

          if [ "$http_code" -ge 200 ] && [ "$http_code" -lt 300 ]; then
            echo "Deployment triggered successfully (HTTP $http_code)"
          else
            echo "Deployment failed with HTTP $http_code"
            exit 1
          fi

