name: Build and Publish Docker Image

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: |
          IMAGE_NAME=ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest

      - name: Trigger DigitalOcean deployment
        if: success()
        run: |
          response=$(curl -X POST \
            -H "Authorization: Bearer ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{}' \
            -w "%{http_code}" \
            -s \
            "https://api.digitalocean.com/v2/apps/5fdf484c-3859-4387-bc2e-533ae5059772/deployments")

          if [[ $response != *"200"* && $response != *"201"* ]]; then
            echo "Deployment trigger failed with response: $response"
            exit 1
          fi

